/*
 * BlockScout API
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {AddressTag} from './AddressTag';
import {WatchlistName} from './WatchlistName';

/**
 * The AddressParam model module.
 * @module model/AddressParam
 * @version 1.0.0
 */
export class AddressParam {
  /**
   * Constructs a new <code>AddressParam</code>.
   * @alias module:model/AddressParam
   * @class
   * @param hash {String} 
   * @param implementationName {String} 
   * @param name {String} 
   * @param isContract {Boolean} 
   * @param privateTags {Array.<module:model/AddressTag>} 
   * @param watchlistNames {Array.<module:model/WatchlistName>} 
   * @param publicTags {Array.<module:model/AddressTag>} 
   * @param isVerified {Boolean} 
   */
  constructor(hash, implementationName, name, isContract, privateTags, watchlistNames, publicTags, isVerified) {
    this.hash = hash;
    this.implementationName = implementationName;
    this.name = name;
    this.isContract = isContract;
    this.privateTags = privateTags;
    this.watchlistNames = watchlistNames;
    this.publicTags = publicTags;
    this.isVerified = isVerified;
  }

  /**
   * Constructs a <code>AddressParam</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AddressParam} obj Optional instance to populate.
   * @return {module:model/AddressParam} The populated <code>AddressParam</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AddressParam();
      if (data.hasOwnProperty('hash'))
        obj.hash = ApiClient.convertToType(data['hash'], 'String');
      if (data.hasOwnProperty('implementation_name'))
        obj.implementationName = ApiClient.convertToType(data['implementation_name'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('is_contract'))
        obj.isContract = ApiClient.convertToType(data['is_contract'], 'Boolean');
      if (data.hasOwnProperty('private_tags'))
        obj.privateTags = ApiClient.convertToType(data['private_tags'], [AddressTag]);
      if (data.hasOwnProperty('watchlist_names'))
        obj.watchlistNames = ApiClient.convertToType(data['watchlist_names'], [WatchlistName]);
      if (data.hasOwnProperty('public_tags'))
        obj.publicTags = ApiClient.convertToType(data['public_tags'], [AddressTag]);
      if (data.hasOwnProperty('is_verified'))
        obj.isVerified = ApiClient.convertToType(data['is_verified'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {String} hash
 */
AddressParam.prototype.hash = undefined;

/**
 * @member {String} implementationName
 */
AddressParam.prototype.implementationName = undefined;

/**
 * @member {String} name
 */
AddressParam.prototype.name = undefined;

/**
 * @member {Boolean} isContract
 */
AddressParam.prototype.isContract = undefined;

/**
 * @member {Array.<module:model/AddressTag>} privateTags
 */
AddressParam.prototype.privateTags = undefined;

/**
 * @member {Array.<module:model/WatchlistName>} watchlistNames
 */
AddressParam.prototype.watchlistNames = undefined;

/**
 * @member {Array.<module:model/AddressTag>} publicTags
 */
AddressParam.prototype.publicTags = undefined;

/**
 * @member {Boolean} isVerified
 */
AddressParam.prototype.isVerified = undefined;

