/*
 * BlockScout API
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The CoinBalanceHistoryEntry model module.
 * @module model/CoinBalanceHistoryEntry
 * @version 1.0.0
 */
export class CoinBalanceHistoryEntry {
  /**
   * Constructs a new <code>CoinBalanceHistoryEntry</code>.
   * @alias module:model/CoinBalanceHistoryEntry
   * @class
   * @param blockNumber {Number} 
   * @param blockTimestamp {String} 
   * @param delta {String} 
   * @param value {String} 
   */
  constructor(blockNumber, blockTimestamp, delta, value) {
    this.blockNumber = blockNumber;
    this.blockTimestamp = blockTimestamp;
    this.delta = delta;
    this.value = value;
  }

  /**
   * Constructs a <code>CoinBalanceHistoryEntry</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CoinBalanceHistoryEntry} obj Optional instance to populate.
   * @return {module:model/CoinBalanceHistoryEntry} The populated <code>CoinBalanceHistoryEntry</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CoinBalanceHistoryEntry();
      if (data.hasOwnProperty('transaction_hash'))
        obj.transactionHash = ApiClient.convertToType(data['transaction_hash'], 'String');
      if (data.hasOwnProperty('block_number'))
        obj.blockNumber = ApiClient.convertToType(data['block_number'], 'Number');
      if (data.hasOwnProperty('block_timestamp'))
        obj.blockTimestamp = ApiClient.convertToType(data['block_timestamp'], 'String');
      if (data.hasOwnProperty('delta'))
        obj.delta = ApiClient.convertToType(data['delta'], 'String');
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} transactionHash
 */
CoinBalanceHistoryEntry.prototype.transactionHash = undefined;

/**
 * @member {Number} blockNumber
 */
CoinBalanceHistoryEntry.prototype.blockNumber = undefined;

/**
 * @member {String} blockTimestamp
 */
CoinBalanceHistoryEntry.prototype.blockTimestamp = undefined;

/**
 * @member {String} delta
 */
CoinBalanceHistoryEntry.prototype.delta = undefined;

/**
 * @member {String} value
 */
CoinBalanceHistoryEntry.prototype.value = undefined;

