/*
 * BlockScout API
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ContractSource model module.
 * @module model/ContractSource
 * @version 1.0.0
 */
export class ContractSource {
  /**
   * Constructs a new <code>ContractSource</code>.
   * @alias module:model/ContractSource
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ContractSource</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ContractSource} obj Optional instance to populate.
   * @return {module:model/ContractSource} The populated <code>ContractSource</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ContractSource();
      if (data.hasOwnProperty('file_path'))
        obj.filePath = ApiClient.convertToType(data['file_path'], 'String');
      if (data.hasOwnProperty('source_code'))
        obj.sourceCode = ApiClient.convertToType(data['source_code'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} filePath
 */
ContractSource.prototype.filePath = undefined;

/**
 * @member {String} sourceCode
 */
ContractSource.prototype.sourceCode = undefined;

