/*
 * BlockScout API
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {DecodedInputLogParameter} from './DecodedInputLogParameter';

/**
 * The DecodedInputLog model module.
 * @module model/DecodedInputLog
 * @version 1.0.0
 */
export class DecodedInputLog {
  /**
   * Constructs a new <code>DecodedInputLog</code>.
   * @alias module:model/DecodedInputLog
   * @class
   * @param methodCall {String} 
   * @param methodId {String} 
   * @param parameters {Array.<module:model/DecodedInputLogParameter>} 
   */
  constructor(methodCall, methodId, parameters) {
    this.methodCall = methodCall;
    this.methodId = methodId;
    this.parameters = parameters;
  }

  /**
   * Constructs a <code>DecodedInputLog</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DecodedInputLog} obj Optional instance to populate.
   * @return {module:model/DecodedInputLog} The populated <code>DecodedInputLog</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DecodedInputLog();
      if (data.hasOwnProperty('method_call'))
        obj.methodCall = ApiClient.convertToType(data['method_call'], 'String');
      if (data.hasOwnProperty('method_id'))
        obj.methodId = ApiClient.convertToType(data['method_id'], 'String');
      if (data.hasOwnProperty('parameters'))
        obj.parameters = ApiClient.convertToType(data['parameters'], [DecodedInputLogParameter]);
    }
    return obj;
  }
}

/**
 * @member {String} methodCall
 */
DecodedInputLog.prototype.methodCall = undefined;

/**
 * @member {String} methodId
 */
DecodedInputLog.prototype.methodId = undefined;

/**
 * @member {Array.<module:model/DecodedInputLogParameter>} parameters
 */
DecodedInputLog.prototype.parameters = undefined;

