/*
 * BlockScout API
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The DecodedInputParameter model module.
 * @module model/DecodedInputParameter
 * @version 1.0.0
 */
export class DecodedInputParameter {
  /**
   * Constructs a new <code>DecodedInputParameter</code>.
   * @alias module:model/DecodedInputParameter
   * @class
   * @param name {String} 
   * @param type {String} 
   * @param value {String} 
   */
  constructor(name, type, value) {
    this.name = name;
    this.type = type;
    this.value = value;
  }

  /**
   * Constructs a <code>DecodedInputParameter</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DecodedInputParameter} obj Optional instance to populate.
   * @return {module:model/DecodedInputParameter} The populated <code>DecodedInputParameter</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DecodedInputParameter();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
DecodedInputParameter.prototype.name = undefined;

/**
 * @member {String} type
 */
DecodedInputParameter.prototype.type = undefined;

/**
 * @member {String} value
 */
DecodedInputParameter.prototype.value = undefined;

