/*
 * BlockScout API
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {AddressWithTxCount} from './AddressWithTxCount';

/**
 * The InlineResponse20011 model module.
 * @module model/InlineResponse20011
 * @version 1.0.0
 */
export class InlineResponse20011 {
  /**
   * Constructs a new <code>InlineResponse20011</code>.
   * @alias module:model/InlineResponse20011
   * @class
   * @param exchangeRate {String} 
   * @param totalSupply {String} 
   * @param items {Array.<module:model/AddressWithTxCount>} 
   * @param nextPageParams {Object} 
   */
  constructor(exchangeRate, totalSupply, items, nextPageParams) {
    this.exchangeRate = exchangeRate;
    this.totalSupply = totalSupply;
    this.items = items;
    this.nextPageParams = nextPageParams;
  }

  /**
   * Constructs a <code>InlineResponse20011</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse20011} obj Optional instance to populate.
   * @return {module:model/InlineResponse20011} The populated <code>InlineResponse20011</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse20011();
      if (data.hasOwnProperty('exchange_rate'))
        obj.exchangeRate = ApiClient.convertToType(data['exchange_rate'], 'String');
      if (data.hasOwnProperty('total_supply'))
        obj.totalSupply = ApiClient.convertToType(data['total_supply'], 'String');
      if (data.hasOwnProperty('items'))
        obj.items = ApiClient.convertToType(data['items'], [AddressWithTxCount]);
      if (data.hasOwnProperty('next_page_params'))
        obj.nextPageParams = ApiClient.convertToType(data['next_page_params'], Object);
    }
    return obj;
  }
}

/**
 * @member {String} exchangeRate
 */
InlineResponse20011.prototype.exchangeRate = undefined;

/**
 * @member {String} totalSupply
 */
InlineResponse20011.prototype.totalSupply = undefined;

/**
 * @member {Array.<module:model/AddressWithTxCount>} items
 */
InlineResponse20011.prototype.items = undefined;

/**
 * @member {Object} nextPageParams
 */
InlineResponse20011.prototype.nextPageParams = undefined;

