/*
 * BlockScout API
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The InlineResponse20027 model module.
 * @module model/InlineResponse20027
 * @version 1.0.0
 */
export class InlineResponse20027 {
  /**
   * Constructs a new <code>InlineResponse20027</code>.
   * @alias module:model/InlineResponse20027
   * @class
   * @param jsonRpcUrl {String} 
   */
  constructor(jsonRpcUrl) {
    this.jsonRpcUrl = jsonRpcUrl;
  }

  /**
   * Constructs a <code>InlineResponse20027</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse20027} obj Optional instance to populate.
   * @return {module:model/InlineResponse20027} The populated <code>InlineResponse20027</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse20027();
      if (data.hasOwnProperty('json_rpc_url'))
        obj.jsonRpcUrl = ApiClient.convertToType(data['json_rpc_url'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} jsonRpcUrl
 */
InlineResponse20027.prototype.jsonRpcUrl = undefined;

