/*
 * BlockScout API
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {AddressParam} from './AddressParam';

/**
 * The InternalTransaction model module.
 * @module model/InternalTransaction
 * @version 1.0.0
 */
export class InternalTransaction {
  /**
   * Constructs a new <code>InternalTransaction</code>.
   * @alias module:model/InternalTransaction
   * @class
   * @param block {Number} 
   * @param createdContract {module:model/AddressParam} 
   * @param error {String} 
   * @param from {module:model/AddressParam} 
   * @param gasLimit {String} 
   * @param index {Number} 
   * @param success {Boolean} 
   * @param timestamp {String} 
   * @param to {module:model/AddressParam} 
   * @param transactionHash {String} 
   * @param type {String} 
   * @param value {String} 
   */
  constructor(block, createdContract, error, from, gasLimit, index, success, timestamp, to, transactionHash, type, value) {
    this.block = block;
    this.createdContract = createdContract;
    this.error = error;
    this.from = from;
    this.gasLimit = gasLimit;
    this.index = index;
    this.success = success;
    this.timestamp = timestamp;
    this.to = to;
    this.transactionHash = transactionHash;
    this.type = type;
    this.value = value;
  }

  /**
   * Constructs a <code>InternalTransaction</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InternalTransaction} obj Optional instance to populate.
   * @return {module:model/InternalTransaction} The populated <code>InternalTransaction</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InternalTransaction();
      if (data.hasOwnProperty('block'))
        obj.block = ApiClient.convertToType(data['block'], 'Number');
      if (data.hasOwnProperty('created_contract'))
        obj.createdContract = AddressParam.constructFromObject(data['created_contract']);
      if (data.hasOwnProperty('error'))
        obj.error = ApiClient.convertToType(data['error'], 'String');
      if (data.hasOwnProperty('from'))
        obj.from = AddressParam.constructFromObject(data['from']);
      if (data.hasOwnProperty('gas_limit'))
        obj.gasLimit = ApiClient.convertToType(data['gas_limit'], 'String');
      if (data.hasOwnProperty('index'))
        obj.index = ApiClient.convertToType(data['index'], 'Number');
      if (data.hasOwnProperty('success'))
        obj.success = ApiClient.convertToType(data['success'], 'Boolean');
      if (data.hasOwnProperty('timestamp'))
        obj.timestamp = ApiClient.convertToType(data['timestamp'], 'String');
      if (data.hasOwnProperty('to'))
        obj.to = AddressParam.constructFromObject(data['to']);
      if (data.hasOwnProperty('transaction_hash'))
        obj.transactionHash = ApiClient.convertToType(data['transaction_hash'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} block
 */
InternalTransaction.prototype.block = undefined;

/**
 * @member {module:model/AddressParam} createdContract
 */
InternalTransaction.prototype.createdContract = undefined;

/**
 * @member {String} error
 */
InternalTransaction.prototype.error = undefined;

/**
 * @member {module:model/AddressParam} from
 */
InternalTransaction.prototype.from = undefined;

/**
 * @member {String} gasLimit
 */
InternalTransaction.prototype.gasLimit = undefined;

/**
 * @member {Number} index
 */
InternalTransaction.prototype.index = undefined;

/**
 * @member {Boolean} success
 */
InternalTransaction.prototype.success = undefined;

/**
 * @member {String} timestamp
 */
InternalTransaction.prototype.timestamp = undefined;

/**
 * @member {module:model/AddressParam} to
 */
InternalTransaction.prototype.to = undefined;

/**
 * @member {String} transactionHash
 */
InternalTransaction.prototype.transactionHash = undefined;

/**
 * @member {String} type
 */
InternalTransaction.prototype.type = undefined;

/**
 * @member {String} value
 */
InternalTransaction.prototype.value = undefined;

