/*
 * BlockScout API
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The OneOfStateChangeChange model module.
 * @module model/OneOfStateChangeChange
 * @version 1.0.0
 */
export class OneOfStateChangeChange {
  /**
   * Constructs a new <code>OneOfStateChangeChange</code>.
   * @alias module:model/OneOfStateChangeChange
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>OneOfStateChangeChange</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OneOfStateChangeChange} obj Optional instance to populate.
   * @return {module:model/OneOfStateChangeChange} The populated <code>OneOfStateChangeChange</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OneOfStateChangeChange();
    }
    return obj;
  }
}
