/*
 * BlockScout API
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The OutputAndNames model module.
 * @module model/OutputAndNames
 * @version 1.0.0
 */
export class OutputAndNames {
  /**
   * Constructs a new <code>OutputAndNames</code>.
   * @alias module:model/OutputAndNames
   * @class
   * @param output {Array} 
   * @param names {Array} 
   */
  constructor(output, names) {
    this.output = output;
    this.names = names;
  }

  /**
   * Constructs a <code>OutputAndNames</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OutputAndNames} obj Optional instance to populate.
   * @return {module:model/OutputAndNames} The populated <code>OutputAndNames</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OutputAndNames();
      if (data.hasOwnProperty('output'))
        obj.output = ApiClient.convertToType(data['output'], Array);
      if (data.hasOwnProperty('names'))
        obj.names = ApiClient.convertToType(data['names'], Array);
    }
    return obj;
  }
}

/**
 * @member {Array} output
 */
OutputAndNames.prototype.output = undefined;

/**
 * @member {Array} names
 */
OutputAndNames.prototype.names = undefined;

// Implement OneOfReadMethodResponseResult interface:
