/*
 * BlockScout API
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The RawTraceCreateAction model module.
 * @module model/RawTraceCreateAction
 * @version 1.0.0
 */
export class RawTraceCreateAction {
  /**
   * Constructs a new <code>RawTraceCreateAction</code>.
   * @alias module:model/RawTraceCreateAction
   * @class
   * @param from {String} 
   * @param gas {String} 
   * @param init {String} 
   * @param value {String} 
   */
  constructor(from, gas, init, value) {
    this.from = from;
    this.gas = gas;
    this.init = init;
    this.value = value;
  }

  /**
   * Constructs a <code>RawTraceCreateAction</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RawTraceCreateAction} obj Optional instance to populate.
   * @return {module:model/RawTraceCreateAction} The populated <code>RawTraceCreateAction</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RawTraceCreateAction();
      if (data.hasOwnProperty('from'))
        obj.from = ApiClient.convertToType(data['from'], 'String');
      if (data.hasOwnProperty('gas'))
        obj.gas = ApiClient.convertToType(data['gas'], 'String');
      if (data.hasOwnProperty('init'))
        obj.init = ApiClient.convertToType(data['init'], 'String');
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} from
 */
RawTraceCreateAction.prototype.from = undefined;

/**
 * @member {String} gas
 */
RawTraceCreateAction.prototype.gas = undefined;

/**
 * @member {String} init
 */
RawTraceCreateAction.prototype.init = undefined;

/**
 * @member {String} value
 */
RawTraceCreateAction.prototype.value = undefined;

// Implement OneOfRawTraceAction interface:
