/*
 * BlockScout API
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The RawTraceCallResult model module.
 * @module model/RawTraceCallResult
 * @version 1.0.0
 */
export class RawTraceCallResult {
  /**
   * Constructs a new <code>RawTraceCallResult</code>.
   * @alias module:model/RawTraceCallResult
   * @class
   * @param gasUsed {String} 
   * @param output {String} 
   */
  constructor(gasUsed, output) {
    this.gasUsed = gasUsed;
    this.output = output;
  }

  /**
   * Constructs a <code>RawTraceCallResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RawTraceCallResult} obj Optional instance to populate.
   * @return {module:model/RawTraceCallResult} The populated <code>RawTraceCallResult</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RawTraceCallResult();
      if (data.hasOwnProperty('gasUsed'))
        obj.gasUsed = ApiClient.convertToType(data['gasUsed'], 'String');
      if (data.hasOwnProperty('output'))
        obj.output = ApiClient.convertToType(data['output'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} gasUsed
 */
RawTraceCallResult.prototype.gasUsed = undefined;

/**
 * @member {String} output
 */
RawTraceCallResult.prototype.output = undefined;

// Implement OneOfRawTraceResult interface:
