/*
 * BlockScout API
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The RawTraceSelfDestructAction model module.
 * @module model/RawTraceSelfDestructAction
 * @version 1.0.0
 */
export class RawTraceSelfDestructAction {
  /**
   * Constructs a new <code>RawTraceSelfDestructAction</code>.
   * @alias module:model/RawTraceSelfDestructAction
   * @class
   * @param address {String} 
   * @param balance {String} 
   * @param refundAddress {String} 
   */
  constructor(address, balance, refundAddress) {
    this.address = address;
    this.balance = balance;
    this.refundAddress = refundAddress;
  }

  /**
   * Constructs a <code>RawTraceSelfDestructAction</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RawTraceSelfDestructAction} obj Optional instance to populate.
   * @return {module:model/RawTraceSelfDestructAction} The populated <code>RawTraceSelfDestructAction</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RawTraceSelfDestructAction();
      if (data.hasOwnProperty('address'))
        obj.address = ApiClient.convertToType(data['address'], 'String');
      if (data.hasOwnProperty('balance'))
        obj.balance = ApiClient.convertToType(data['balance'], 'String');
      if (data.hasOwnProperty('refundAddress'))
        obj.refundAddress = ApiClient.convertToType(data['refundAddress'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} address
 */
RawTraceSelfDestructAction.prototype.address = undefined;

/**
 * @member {String} balance
 */
RawTraceSelfDestructAction.prototype.balance = undefined;

/**
 * @member {String} refundAddress
 */
RawTraceSelfDestructAction.prototype.refundAddress = undefined;

// Implement OneOfRawTraceAction interface:
