/*
 * BlockScout API
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ReadMethodQueryBody model module.
 * @module model/ReadMethodQueryBody
 * @version 1.0.0
 */
export class ReadMethodQueryBody {
  /**
   * Constructs a new <code>ReadMethodQueryBody</code>.
   * @alias module:model/ReadMethodQueryBody
   * @class
   * @param args {Array} 
   * @param methodId {String} 
   */
  constructor(args, methodId) {
    this.args = args;
    this.methodId = methodId;
  }

  /**
   * Constructs a <code>ReadMethodQueryBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ReadMethodQueryBody} obj Optional instance to populate.
   * @return {module:model/ReadMethodQueryBody} The populated <code>ReadMethodQueryBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ReadMethodQueryBody();
      if (data.hasOwnProperty('args'))
        obj.args = ApiClient.convertToType(data['args'], Array);
      if (data.hasOwnProperty('method_id'))
        obj.methodId = ApiClient.convertToType(data['method_id'], 'String');
      if (data.hasOwnProperty('from'))
        obj.from = ApiClient.convertToType(data['from'], 'String');
      if (data.hasOwnProperty('contract_type'))
        obj.contractType = ApiClient.convertToType(data['contract_type'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Array} args
 */
ReadMethodQueryBody.prototype.args = undefined;

/**
 * @member {String} methodId
 */
ReadMethodQueryBody.prototype.methodId = undefined;

/**
 * @member {String} from
 */
ReadMethodQueryBody.prototype.from = undefined;

/**
 * @member {String} contractType
 */
ReadMethodQueryBody.prototype.contractType = undefined;

