/*
 * BlockScout API
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Reward model module.
 * @module model/Reward
 * @version 1.0.0
 */
export class Reward {
  /**
   * Constructs a new <code>Reward</code>.
   * @alias module:model/Reward
   * @class
   * @param reward {Number} 
   * @param type {String} 
   */
  constructor(reward, type) {
    this.reward = reward;
    this.type = type;
  }

  /**
   * Constructs a <code>Reward</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Reward} obj Optional instance to populate.
   * @return {module:model/Reward} The populated <code>Reward</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Reward();
      if (data.hasOwnProperty('reward'))
        obj.reward = ApiClient.convertToType(data['reward'], 'Number');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} reward
 */
Reward.prototype.reward = undefined;

/**
 * @member {String} type
 */
Reward.prototype.type = undefined;

