/*
 * BlockScout API
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The SearchResultBlock model module.
 * @module model/SearchResultBlock
 * @version 1.0.0
 */
export class SearchResultBlock {
  /**
   * Constructs a new <code>SearchResultBlock</code>.
   * @alias module:model/SearchResultBlock
   * @class
   * @param blockHash {String} 
   * @param blockNumber {Number} 
   * @param timestamp {String} 
   * @param type {String} 
   * @param url {String} 
   */
  constructor(blockHash, blockNumber, timestamp, type, url) {
    this.blockHash = blockHash;
    this.blockNumber = blockNumber;
    this.timestamp = timestamp;
    this.type = type;
    this.url = url;
  }

  /**
   * Constructs a <code>SearchResultBlock</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SearchResultBlock} obj Optional instance to populate.
   * @return {module:model/SearchResultBlock} The populated <code>SearchResultBlock</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SearchResultBlock();
      if (data.hasOwnProperty('block_hash'))
        obj.blockHash = ApiClient.convertToType(data['block_hash'], 'String');
      if (data.hasOwnProperty('block_number'))
        obj.blockNumber = ApiClient.convertToType(data['block_number'], 'Number');
      if (data.hasOwnProperty('timestamp'))
        obj.timestamp = ApiClient.convertToType(data['timestamp'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('url'))
        obj.url = ApiClient.convertToType(data['url'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} blockHash
 */
SearchResultBlock.prototype.blockHash = undefined;

/**
 * @member {Number} blockNumber
 */
SearchResultBlock.prototype.blockNumber = undefined;

/**
 * @member {String} timestamp
 */
SearchResultBlock.prototype.timestamp = undefined;

/**
 * @member {String} type
 */
SearchResultBlock.prototype.type = undefined;

/**
 * @member {String} url
 */
SearchResultBlock.prototype.url = undefined;

// Implement OneOfinlineResponse200ItemsItems interface:
