/*
 * BlockScout API
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The SearchResultToken model module.
 * @module model/SearchResultToken
 * @version 1.0.0
 */
export class SearchResultToken {
  /**
   * Constructs a new <code>SearchResultToken</code>.
   * @alias module:model/SearchResultToken
   * @class
   * @param address {String} 
   * @param addressUrl {String} 
   * @param exchangeRate {String} 
   * @param iconUrl {String} 
   * @param isSmartContractVerified {Boolean} 
   * @param name {String} 
   * @param symbol {String} 
   * @param tokenType {String} 
   * @param tokenUrl {String} 
   * @param totalSupply {String} 
   * @param type {String} 
   */
  constructor(address, addressUrl, exchangeRate, iconUrl, isSmartContractVerified, name, symbol, tokenType, tokenUrl, totalSupply, type) {
    this.address = address;
    this.addressUrl = addressUrl;
    this.exchangeRate = exchangeRate;
    this.iconUrl = iconUrl;
    this.isSmartContractVerified = isSmartContractVerified;
    this.name = name;
    this.symbol = symbol;
    this.tokenType = tokenType;
    this.tokenUrl = tokenUrl;
    this.totalSupply = totalSupply;
    this.type = type;
  }

  /**
   * Constructs a <code>SearchResultToken</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SearchResultToken} obj Optional instance to populate.
   * @return {module:model/SearchResultToken} The populated <code>SearchResultToken</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SearchResultToken();
      if (data.hasOwnProperty('address'))
        obj.address = ApiClient.convertToType(data['address'], 'String');
      if (data.hasOwnProperty('address_url'))
        obj.addressUrl = ApiClient.convertToType(data['address_url'], 'String');
      if (data.hasOwnProperty('exchange_rate'))
        obj.exchangeRate = ApiClient.convertToType(data['exchange_rate'], 'String');
      if (data.hasOwnProperty('icon_url'))
        obj.iconUrl = ApiClient.convertToType(data['icon_url'], 'String');
      if (data.hasOwnProperty('is_smart_contract_verified'))
        obj.isSmartContractVerified = ApiClient.convertToType(data['is_smart_contract_verified'], 'Boolean');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('symbol'))
        obj.symbol = ApiClient.convertToType(data['symbol'], 'String');
      if (data.hasOwnProperty('token_type'))
        obj.tokenType = ApiClient.convertToType(data['token_type'], 'String');
      if (data.hasOwnProperty('token_url'))
        obj.tokenUrl = ApiClient.convertToType(data['token_url'], 'String');
      if (data.hasOwnProperty('total_supply'))
        obj.totalSupply = ApiClient.convertToType(data['total_supply'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} address
 */
SearchResultToken.prototype.address = undefined;

/**
 * @member {String} addressUrl
 */
SearchResultToken.prototype.addressUrl = undefined;

/**
 * @member {String} exchangeRate
 */
SearchResultToken.prototype.exchangeRate = undefined;

/**
 * @member {String} iconUrl
 */
SearchResultToken.prototype.iconUrl = undefined;

/**
 * @member {Boolean} isSmartContractVerified
 */
SearchResultToken.prototype.isSmartContractVerified = undefined;

/**
 * @member {String} name
 */
SearchResultToken.prototype.name = undefined;

/**
 * @member {String} symbol
 */
SearchResultToken.prototype.symbol = undefined;

/**
 * @member {String} tokenType
 */
SearchResultToken.prototype.tokenType = undefined;

/**
 * @member {String} tokenUrl
 */
SearchResultToken.prototype.tokenUrl = undefined;

/**
 * @member {String} totalSupply
 */
SearchResultToken.prototype.totalSupply = undefined;

/**
 * @member {String} type
 */
SearchResultToken.prototype.type = undefined;

// Implement OneOfinlineResponse200ItemsItems interface:
