/*
 * BlockScout API
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The SearchResultTransaction model module.
 * @module model/SearchResultTransaction
 * @version 1.0.0
 */
export class SearchResultTransaction {
  /**
   * Constructs a new <code>SearchResultTransaction</code>.
   * @alias module:model/SearchResultTransaction
   * @class
   * @param timestamp {String} 
   * @param txHash {String} 
   * @param type {String} 
   * @param url {String} 
   */
  constructor(timestamp, txHash, type, url) {
    this.timestamp = timestamp;
    this.txHash = txHash;
    this.type = type;
    this.url = url;
  }

  /**
   * Constructs a <code>SearchResultTransaction</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SearchResultTransaction} obj Optional instance to populate.
   * @return {module:model/SearchResultTransaction} The populated <code>SearchResultTransaction</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SearchResultTransaction();
      if (data.hasOwnProperty('timestamp'))
        obj.timestamp = ApiClient.convertToType(data['timestamp'], 'String');
      if (data.hasOwnProperty('tx_hash'))
        obj.txHash = ApiClient.convertToType(data['tx_hash'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('url'))
        obj.url = ApiClient.convertToType(data['url'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} timestamp
 */
SearchResultTransaction.prototype.timestamp = undefined;

/**
 * @member {String} txHash
 */
SearchResultTransaction.prototype.txHash = undefined;

/**
 * @member {String} type
 */
SearchResultTransaction.prototype.type = undefined;

/**
 * @member {String} url
 */
SearchResultTransaction.prototype.url = undefined;

// Implement OneOfinlineResponse200ItemsItems interface:
