/*
 * BlockScout API
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {AddressParam} from './AddressParam';

/**
 * The SmartContractForList model module.
 * @module model/SmartContractForList
 * @version 1.0.0
 */
export class SmartContractForList {
  /**
   * Constructs a new <code>SmartContractForList</code>.
   * @alias module:model/SmartContractForList
   * @class
   * @param address {module:model/AddressParam} 
   * @param coinBalance {String} 
   * @param compilerVersion {String} 
   * @param language {String} 
   * @param hasConstructorArgs {Boolean} 
   * @param optimizationEnabled {Boolean} 
   * @param txCount {Number} 
   * @param verifiedAt {String} 
   */
  constructor(address, coinBalance, compilerVersion, language, hasConstructorArgs, optimizationEnabled, txCount, verifiedAt) {
    this.address = address;
    this.coinBalance = coinBalance;
    this.compilerVersion = compilerVersion;
    this.language = language;
    this.hasConstructorArgs = hasConstructorArgs;
    this.optimizationEnabled = optimizationEnabled;
    this.txCount = txCount;
    this.verifiedAt = verifiedAt;
  }

  /**
   * Constructs a <code>SmartContractForList</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SmartContractForList} obj Optional instance to populate.
   * @return {module:model/SmartContractForList} The populated <code>SmartContractForList</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SmartContractForList();
      if (data.hasOwnProperty('address'))
        obj.address = AddressParam.constructFromObject(data['address']);
      if (data.hasOwnProperty('coin_balance'))
        obj.coinBalance = ApiClient.convertToType(data['coin_balance'], 'String');
      if (data.hasOwnProperty('compiler_version'))
        obj.compilerVersion = ApiClient.convertToType(data['compiler_version'], 'String');
      if (data.hasOwnProperty('language'))
        obj.language = ApiClient.convertToType(data['language'], 'String');
      if (data.hasOwnProperty('has_constructor_args'))
        obj.hasConstructorArgs = ApiClient.convertToType(data['has_constructor_args'], 'Boolean');
      if (data.hasOwnProperty('optimization_enabled'))
        obj.optimizationEnabled = ApiClient.convertToType(data['optimization_enabled'], 'Boolean');
      if (data.hasOwnProperty('tx_count'))
        obj.txCount = ApiClient.convertToType(data['tx_count'], 'Number');
      if (data.hasOwnProperty('verified_at'))
        obj.verifiedAt = ApiClient.convertToType(data['verified_at'], 'String');
      if (data.hasOwnProperty('market_cap'))
        obj.marketCap = ApiClient.convertToType(data['market_cap'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {module:model/AddressParam} address
 */
SmartContractForList.prototype.address = undefined;

/**
 * @member {String} coinBalance
 */
SmartContractForList.prototype.coinBalance = undefined;

/**
 * @member {String} compilerVersion
 */
SmartContractForList.prototype.compilerVersion = undefined;

/**
 * @member {String} language
 */
SmartContractForList.prototype.language = undefined;

/**
 * @member {Boolean} hasConstructorArgs
 */
SmartContractForList.prototype.hasConstructorArgs = undefined;

/**
 * @member {Boolean} optimizationEnabled
 */
SmartContractForList.prototype.optimizationEnabled = undefined;

/**
 * @member {Number} txCount
 */
SmartContractForList.prototype.txCount = undefined;

/**
 * @member {String} verifiedAt
 */
SmartContractForList.prototype.verifiedAt = undefined;

/**
 * @member {Number} marketCap
 */
SmartContractForList.prototype.marketCap = undefined;

