/*
 * BlockScout API
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {AddressParam} from './AddressParam';
import {TokenInfo} from './TokenInfo';

/**
 * The StateChange model module.
 * @module model/StateChange
 * @version 1.0.0
 */
export class StateChange {
  /**
   * Constructs a new <code>StateChange</code>.
   * @alias module:model/StateChange
   * @class
   * @param type {String} 
   * @param isMiner {Boolean} 
   * @param address {module:model/AddressParam} 
   */
  constructor(type, isMiner, address) {
    this.type = type;
    this.isMiner = isMiner;
    this.address = address;
  }

  /**
   * Constructs a <code>StateChange</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/StateChange} obj Optional instance to populate.
   * @return {module:model/StateChange} The populated <code>StateChange</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new StateChange();
      if (data.hasOwnProperty('token'))
        obj.token = TokenInfo.constructFromObject(data['token']);
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('is_miner'))
        obj.isMiner = ApiClient.convertToType(data['is_miner'], 'Boolean');
      if (data.hasOwnProperty('address'))
        obj.address = AddressParam.constructFromObject(data['address']);
      if (data.hasOwnProperty('balance_before'))
        obj.balanceBefore = ApiClient.convertToType(data['balance_before'], 'String');
      if (data.hasOwnProperty('balance_after'))
        obj.balanceAfter = ApiClient.convertToType(data['balance_after'], 'String');
      if (data.hasOwnProperty('token_id'))
        obj.tokenId = ApiClient.convertToType(data['token_id'], 'String');
      if (data.hasOwnProperty('change'))
        obj.change = ApiClient.convertToType(data['change'], Object);
    }
    return obj;
  }
}

/**
 * @member {module:model/TokenInfo} token
 */
StateChange.prototype.token = undefined;

/**
 * @member {String} type
 */
StateChange.prototype.type = undefined;

/**
 * @member {Boolean} isMiner
 */
StateChange.prototype.isMiner = undefined;

/**
 * @member {module:model/AddressParam} address
 */
StateChange.prototype.address = undefined;

/**
 * @member {String} balanceBefore
 */
StateChange.prototype.balanceBefore = undefined;

/**
 * @member {String} balanceAfter
 */
StateChange.prototype.balanceAfter = undefined;

/**
 * @member {String} tokenId
 */
StateChange.prototype.tokenId = undefined;

/**
 * @member {Object} change
 */
StateChange.prototype.change = undefined;

