/*
 * BlockScout API
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The StatsResponse model module.
 * @module model/StatsResponse
 * @version 1.0.0
 */
export class StatsResponse {
  /**
   * Constructs a new <code>StatsResponse</code>.
   * @alias module:model/StatsResponse
   * @class
   * @param totalBlocks {String} 
   * @param totalAddresses {String} 
   * @param totalTransactions {String} 
   * @param averageBlockTime {Number} 
   * @param coinPrice {String} 
   * @param totalGasUsed {String} 
   * @param transactionsToday {String} 
   * @param gasUsedToday {String} 
   * @param gasPrices {Object} 
   * @param staticGasPrice {String} 
   * @param marketCap {String} 
   * @param networkUtilizationPercentage {Number} 
   */
  constructor(totalBlocks, totalAddresses, totalTransactions, averageBlockTime, coinPrice, totalGasUsed, transactionsToday, gasUsedToday, gasPrices, staticGasPrice, marketCap, networkUtilizationPercentage) {
    this.totalBlocks = totalBlocks;
    this.totalAddresses = totalAddresses;
    this.totalTransactions = totalTransactions;
    this.averageBlockTime = averageBlockTime;
    this.coinPrice = coinPrice;
    this.totalGasUsed = totalGasUsed;
    this.transactionsToday = transactionsToday;
    this.gasUsedToday = gasUsedToday;
    this.gasPrices = gasPrices;
    this.staticGasPrice = staticGasPrice;
    this.marketCap = marketCap;
    this.networkUtilizationPercentage = networkUtilizationPercentage;
  }

  /**
   * Constructs a <code>StatsResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/StatsResponse} obj Optional instance to populate.
   * @return {module:model/StatsResponse} The populated <code>StatsResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new StatsResponse();
      if (data.hasOwnProperty('total_blocks'))
        obj.totalBlocks = ApiClient.convertToType(data['total_blocks'], 'String');
      if (data.hasOwnProperty('total_addresses'))
        obj.totalAddresses = ApiClient.convertToType(data['total_addresses'], 'String');
      if (data.hasOwnProperty('total_transactions'))
        obj.totalTransactions = ApiClient.convertToType(data['total_transactions'], 'String');
      if (data.hasOwnProperty('average_block_time'))
        obj.averageBlockTime = ApiClient.convertToType(data['average_block_time'], 'Number');
      if (data.hasOwnProperty('coin_price'))
        obj.coinPrice = ApiClient.convertToType(data['coin_price'], 'String');
      if (data.hasOwnProperty('total_gas_used'))
        obj.totalGasUsed = ApiClient.convertToType(data['total_gas_used'], 'String');
      if (data.hasOwnProperty('transactions_today'))
        obj.transactionsToday = ApiClient.convertToType(data['transactions_today'], 'String');
      if (data.hasOwnProperty('gas_used_today'))
        obj.gasUsedToday = ApiClient.convertToType(data['gas_used_today'], 'String');
      if (data.hasOwnProperty('gas_prices'))
        obj.gasPrices = ApiClient.convertToType(data['gas_prices'], Object);
      if (data.hasOwnProperty('static_gas_price'))
        obj.staticGasPrice = ApiClient.convertToType(data['static_gas_price'], 'String');
      if (data.hasOwnProperty('market_cap'))
        obj.marketCap = ApiClient.convertToType(data['market_cap'], 'String');
      if (data.hasOwnProperty('network_utilization_percentage'))
        obj.networkUtilizationPercentage = ApiClient.convertToType(data['network_utilization_percentage'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} totalBlocks
 */
StatsResponse.prototype.totalBlocks = undefined;

/**
 * @member {String} totalAddresses
 */
StatsResponse.prototype.totalAddresses = undefined;

/**
 * @member {String} totalTransactions
 */
StatsResponse.prototype.totalTransactions = undefined;

/**
 * @member {Number} averageBlockTime
 */
StatsResponse.prototype.averageBlockTime = undefined;

/**
 * @member {String} coinPrice
 */
StatsResponse.prototype.coinPrice = undefined;

/**
 * @member {String} totalGasUsed
 */
StatsResponse.prototype.totalGasUsed = undefined;

/**
 * @member {String} transactionsToday
 */
StatsResponse.prototype.transactionsToday = undefined;

/**
 * @member {String} gasUsedToday
 */
StatsResponse.prototype.gasUsedToday = undefined;

/**
 * @member {Object} gasPrices
 */
StatsResponse.prototype.gasPrices = undefined;

/**
 * @member {String} staticGasPrice
 */
StatsResponse.prototype.staticGasPrice = undefined;

/**
 * @member {String} marketCap
 */
StatsResponse.prototype.marketCap = undefined;

/**
 * @member {Number} networkUtilizationPercentage
 */
StatsResponse.prototype.networkUtilizationPercentage = undefined;

