/*
 * BlockScout API
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The TokenInfo model module.
 * @module model/TokenInfo
 * @version 1.0.0
 */
export class TokenInfo {
  /**
   * Constructs a new <code>TokenInfo</code>.
   * @alias module:model/TokenInfo
   * @class
   * @param circulatingMarketCap {String} 
   * @param iconUrl {String} 
   * @param name {String} 
   * @param decimals {String} 
   * @param symbol {String} 
   * @param address {String} 
   * @param type {String} 
   * @param holders {String} 
   * @param exchangeRate {String} 
   * @param totalSupply {String} 
   */
  constructor(circulatingMarketCap, iconUrl, name, decimals, symbol, address, type, holders, exchangeRate, totalSupply) {
    this.circulatingMarketCap = circulatingMarketCap;
    this.iconUrl = iconUrl;
    this.name = name;
    this.decimals = decimals;
    this.symbol = symbol;
    this.address = address;
    this.type = type;
    this.holders = holders;
    this.exchangeRate = exchangeRate;
    this.totalSupply = totalSupply;
  }

  /**
   * Constructs a <code>TokenInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TokenInfo} obj Optional instance to populate.
   * @return {module:model/TokenInfo} The populated <code>TokenInfo</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TokenInfo();
      if (data.hasOwnProperty('circulating_market_cap'))
        obj.circulatingMarketCap = ApiClient.convertToType(data['circulating_market_cap'], 'String');
      if (data.hasOwnProperty('icon_url'))
        obj.iconUrl = ApiClient.convertToType(data['icon_url'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('decimals'))
        obj.decimals = ApiClient.convertToType(data['decimals'], 'String');
      if (data.hasOwnProperty('symbol'))
        obj.symbol = ApiClient.convertToType(data['symbol'], 'String');
      if (data.hasOwnProperty('address'))
        obj.address = ApiClient.convertToType(data['address'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('holders'))
        obj.holders = ApiClient.convertToType(data['holders'], 'String');
      if (data.hasOwnProperty('exchange_rate'))
        obj.exchangeRate = ApiClient.convertToType(data['exchange_rate'], 'String');
      if (data.hasOwnProperty('total_supply'))
        obj.totalSupply = ApiClient.convertToType(data['total_supply'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} circulatingMarketCap
 */
TokenInfo.prototype.circulatingMarketCap = undefined;

/**
 * @member {String} iconUrl
 */
TokenInfo.prototype.iconUrl = undefined;

/**
 * @member {String} name
 */
TokenInfo.prototype.name = undefined;

/**
 * @member {String} decimals
 */
TokenInfo.prototype.decimals = undefined;

/**
 * @member {String} symbol
 */
TokenInfo.prototype.symbol = undefined;

/**
 * @member {String} address
 */
TokenInfo.prototype.address = undefined;

/**
 * @member {String} type
 */
TokenInfo.prototype.type = undefined;

/**
 * @member {String} holders
 */
TokenInfo.prototype.holders = undefined;

/**
 * @member {String} exchangeRate
 */
TokenInfo.prototype.exchangeRate = undefined;

/**
 * @member {String} totalSupply
 */
TokenInfo.prototype.totalSupply = undefined;

