/*
 * BlockScout API
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {NFTInstance} from './NFTInstance';
import {Token} from './Token';

/**
 * The TokenBalance model module.
 * @module model/TokenBalance
 * @version 1.0.0
 */
export class TokenBalance {
  /**
   * Constructs a new <code>TokenBalance</code>.
   * @alias module:model/TokenBalance
   * @class
   * @param value {String} 
   * @param tokenId {String} 
   * @param token {module:model/Token} 
   */
  constructor(value, tokenId, token) {
    this.value = value;
    this.tokenId = tokenId;
    this.token = token;
  }

  /**
   * Constructs a <code>TokenBalance</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TokenBalance} obj Optional instance to populate.
   * @return {module:model/TokenBalance} The populated <code>TokenBalance</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TokenBalance();
      if (data.hasOwnProperty('token_instance'))
        obj.tokenInstance = NFTInstance.constructFromObject(data['token_instance']);
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], 'String');
      if (data.hasOwnProperty('token_id'))
        obj.tokenId = ApiClient.convertToType(data['token_id'], 'String');
      if (data.hasOwnProperty('token'))
        obj.token = Token.constructFromObject(data['token']);
    }
    return obj;
  }
}

/**
 * @member {module:model/NFTInstance} tokenInstance
 */
TokenBalance.prototype.tokenInstance = undefined;

/**
 * @member {String} value
 */
TokenBalance.prototype.value = undefined;

/**
 * @member {String} tokenId
 */
TokenBalance.prototype.tokenId = undefined;

/**
 * @member {module:model/Token} token
 */
TokenBalance.prototype.token = undefined;

