/*
 * BlockScout API
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The TotalERC721 model module.
 * @module model/TotalERC721
 * @version 1.0.0
 */
export class TotalERC721 {
  /**
   * Constructs a new <code>TotalERC721</code>.
   * @alias module:model/TotalERC721
   * @class
   * @param tokenId {String} 
   */
  constructor(tokenId) {
    this.tokenId = tokenId;
  }

  /**
   * Constructs a <code>TotalERC721</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TotalERC721} obj Optional instance to populate.
   * @return {module:model/TotalERC721} The populated <code>TotalERC721</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TotalERC721();
      if (data.hasOwnProperty('token_id'))
        obj.tokenId = ApiClient.convertToType(data['token_id'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} tokenId
 */
TotalERC721.prototype.tokenId = undefined;

// Implement OneOfTokenTransferTotal interface:
