/*
 * BlockScout API
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The TotalERC1155 model module.
 * @module model/TotalERC1155
 * @version 1.0.0
 */
export class TotalERC1155 {
  /**
   * Constructs a new <code>TotalERC1155</code>.
   * @alias module:model/TotalERC1155
   * @class
   * @param tokenId {String} 
   * @param decimals {String} 
   * @param value {String} 
   */
  constructor(tokenId, decimals, value) {
    this.tokenId = tokenId;
    this.decimals = decimals;
    this.value = value;
  }

  /**
   * Constructs a <code>TotalERC1155</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TotalERC1155} obj Optional instance to populate.
   * @return {module:model/TotalERC1155} The populated <code>TotalERC1155</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TotalERC1155();
      if (data.hasOwnProperty('token_id'))
        obj.tokenId = ApiClient.convertToType(data['token_id'], 'String');
      if (data.hasOwnProperty('decimals'))
        obj.decimals = ApiClient.convertToType(data['decimals'], 'String');
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} tokenId
 */
TotalERC1155.prototype.tokenId = undefined;

/**
 * @member {String} decimals
 */
TotalERC1155.prototype.decimals = undefined;

/**
 * @member {String} value
 */
TotalERC1155.prototype.value = undefined;

// Implement OneOfTokenTransferTotal interface:
