/*
 * BlockScout API
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The TransactionChartItem model module.
 * @module model/TransactionChartItem
 * @version 1.0.0
 */
export class TransactionChartItem {
  /**
   * Constructs a new <code>TransactionChartItem</code>.
   * @alias module:model/TransactionChartItem
   * @class
   * @param _date {String} 
   * @param txCount {Number} 
   */
  constructor(_date, txCount) {
    this._date = _date;
    this.txCount = txCount;
  }

  /**
   * Constructs a <code>TransactionChartItem</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TransactionChartItem} obj Optional instance to populate.
   * @return {module:model/TransactionChartItem} The populated <code>TransactionChartItem</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TransactionChartItem();
      if (data.hasOwnProperty('date'))
        obj._date = ApiClient.convertToType(data['date'], 'String');
      if (data.hasOwnProperty('tx_count'))
        obj.txCount = ApiClient.convertToType(data['tx_count'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} _date
 */
TransactionChartItem.prototype._date = undefined;

/**
 * @member {Number} txCount
 */
TransactionChartItem.prototype.txCount = undefined;

