/*
 * BlockScout API
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {AddressParam} from './AddressParam';

/**
 * The TransactionReward model module.
 * @module model/TransactionReward
 * @version 1.0.0
 */
export class TransactionReward {
  /**
   * Constructs a new <code>TransactionReward</code>.
   * @alias module:model/TransactionReward
   * @class
   * @param types {Object} 
   * @param emissionReward {String} 
   * @param blockHash {String} 
   * @param from {module:model/AddressParam} 
   * @param to {module:model/AddressParam} 
   */
  constructor(types, emissionReward, blockHash, from, to) {
    this.types = types;
    this.emissionReward = emissionReward;
    this.blockHash = blockHash;
    this.from = from;
    this.to = to;
  }

  /**
   * Constructs a <code>TransactionReward</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TransactionReward} obj Optional instance to populate.
   * @return {module:model/TransactionReward} The populated <code>TransactionReward</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TransactionReward();
      if (data.hasOwnProperty('types'))
        obj.types = ApiClient.convertToType(data['types'], Object);
      if (data.hasOwnProperty('emission_reward'))
        obj.emissionReward = ApiClient.convertToType(data['emission_reward'], 'String');
      if (data.hasOwnProperty('block_hash'))
        obj.blockHash = ApiClient.convertToType(data['block_hash'], 'String');
      if (data.hasOwnProperty('from'))
        obj.from = AddressParam.constructFromObject(data['from']);
      if (data.hasOwnProperty('to'))
        obj.to = AddressParam.constructFromObject(data['to']);
    }
    return obj;
  }
}

/**
 * @member {Object} types
 */
TransactionReward.prototype.types = undefined;

/**
 * @member {String} emissionReward
 */
TransactionReward.prototype.emissionReward = undefined;

/**
 * @member {String} blockHash
 */
TransactionReward.prototype.blockHash = undefined;

/**
 * @member {module:model/AddressParam} from
 */
TransactionReward.prototype.from = undefined;

/**
 * @member {module:model/AddressParam} to
 */
TransactionReward.prototype.to = undefined;

