/*
 * BlockScout API
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {AddressParam} from './AddressParam';

/**
 * The Withdrawal model module.
 * @module model/Withdrawal
 * @version 1.0.0
 */
export class Withdrawal {
  /**
   * Constructs a new <code>Withdrawal</code>.
   * @alias module:model/Withdrawal
   * @class
   * @param index {Number} 
   * @param amount {String} 
   * @param validatorIndex {Number} 
   */
  constructor(index, amount, validatorIndex) {
    this.index = index;
    this.amount = amount;
    this.validatorIndex = validatorIndex;
  }

  /**
   * Constructs a <code>Withdrawal</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Withdrawal} obj Optional instance to populate.
   * @return {module:model/Withdrawal} The populated <code>Withdrawal</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Withdrawal();
      if (data.hasOwnProperty('index'))
        obj.index = ApiClient.convertToType(data['index'], 'Number');
      if (data.hasOwnProperty('amount'))
        obj.amount = ApiClient.convertToType(data['amount'], 'String');
      if (data.hasOwnProperty('validator_index'))
        obj.validatorIndex = ApiClient.convertToType(data['validator_index'], 'Number');
      if (data.hasOwnProperty('receiver'))
        obj.receiver = AddressParam.constructFromObject(data['receiver']);
      if (data.hasOwnProperty('block_number'))
        obj.blockNumber = ApiClient.convertToType(data['block_number'], 'Number');
      if (data.hasOwnProperty('timestamp'))
        obj.timestamp = ApiClient.convertToType(data['timestamp'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} index
 */
Withdrawal.prototype.index = undefined;

/**
 * @member {String} amount
 */
Withdrawal.prototype.amount = undefined;

/**
 * @member {Number} validatorIndex
 */
Withdrawal.prototype.validatorIndex = undefined;

/**
 * @member {module:model/AddressParam} receiver
 */
Withdrawal.prototype.receiver = undefined;

/**
 * @member {Number} blockNumber
 */
Withdrawal.prototype.blockNumber = undefined;

/**
 * @member {String} timestamp
 */
Withdrawal.prototype.timestamp = undefined;

