/*
 * BlockScout API
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BlockScoutApi);
  }
}(this, function(expect, BlockScoutApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('AddressCounters', function() {
      beforeEach(function() {
        instance = new BlockScoutApi.AddressCounters();
      });

      it('should create an instance of AddressCounters', function() {
        // TODO: update the code to test AddressCounters
        expect(instance).to.be.a(BlockScoutApi.AddressCounters);
      });

      it('should have the property transactionsCount (base name: "transactions_count")', function() {
        // TODO: update the code to test the property transactionsCount
        expect(instance).to.have.property('transactionsCount');
        // expect(instance.transactionsCount).to.be(expectedValueLiteral);
      });

      it('should have the property tokenTransfersCount (base name: "token_transfers_count")', function() {
        // TODO: update the code to test the property tokenTransfersCount
        expect(instance).to.have.property('tokenTransfersCount');
        // expect(instance.tokenTransfersCount).to.be(expectedValueLiteral);
      });

      it('should have the property gasUsageCount (base name: "gas_usage_count")', function() {
        // TODO: update the code to test the property gasUsageCount
        expect(instance).to.have.property('gasUsageCount');
        // expect(instance.gasUsageCount).to.be(expectedValueLiteral);
      });

      it('should have the property validationsCount (base name: "validations_count")', function() {
        // TODO: update the code to test the property validationsCount
        expect(instance).to.have.property('validationsCount');
        // expect(instance.validationsCount).to.be(expectedValueLiteral);
      });

    });
  });

}));
