/*
 * BlockScout API
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BlockScoutApi);
  }
}(this, function(expect, BlockScoutApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('CoinBalanceHistoryEntry', function() {
      beforeEach(function() {
        instance = new BlockScoutApi.CoinBalanceHistoryEntry();
      });

      it('should create an instance of CoinBalanceHistoryEntry', function() {
        // TODO: update the code to test CoinBalanceHistoryEntry
        expect(instance).to.be.a(BlockScoutApi.CoinBalanceHistoryEntry);
      });

      it('should have the property transactionHash (base name: "transaction_hash")', function() {
        // TODO: update the code to test the property transactionHash
        expect(instance).to.have.property('transactionHash');
        // expect(instance.transactionHash).to.be(expectedValueLiteral);
      });

      it('should have the property blockNumber (base name: "block_number")', function() {
        // TODO: update the code to test the property blockNumber
        expect(instance).to.have.property('blockNumber');
        // expect(instance.blockNumber).to.be(expectedValueLiteral);
      });

      it('should have the property blockTimestamp (base name: "block_timestamp")', function() {
        // TODO: update the code to test the property blockTimestamp
        expect(instance).to.have.property('blockTimestamp');
        // expect(instance.blockTimestamp).to.be(expectedValueLiteral);
      });

      it('should have the property delta (base name: "delta")', function() {
        // TODO: update the code to test the property delta
        expect(instance).to.have.property('delta');
        // expect(instance.delta).to.be(expectedValueLiteral);
      });

      it('should have the property value (base name: "value")', function() {
        // TODO: update the code to test the property value
        expect(instance).to.have.property('value');
        // expect(instance.value).to.be(expectedValueLiteral);
      });

    });
  });

}));
