/*
 * BlockScout API
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BlockScoutApi);
  }
}(this, function(expect, BlockScoutApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ContractSource', function() {
      beforeEach(function() {
        instance = new BlockScoutApi.ContractSource();
      });

      it('should create an instance of ContractSource', function() {
        // TODO: update the code to test ContractSource
        expect(instance).to.be.a(BlockScoutApi.ContractSource);
      });

      it('should have the property filePath (base name: "file_path")', function() {
        // TODO: update the code to test the property filePath
        expect(instance).to.have.property('filePath');
        // expect(instance.filePath).to.be(expectedValueLiteral);
      });

      it('should have the property sourceCode (base name: "source_code")', function() {
        // TODO: update the code to test the property sourceCode
        expect(instance).to.have.property('sourceCode');
        // expect(instance.sourceCode).to.be(expectedValueLiteral);
      });

    });
  });

}));
