/*
 * BlockScout API
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BlockScoutApi);
  }
}(this, function(expect, BlockScoutApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('DecodedInput', function() {
      beforeEach(function() {
        instance = new BlockScoutApi.DecodedInput();
      });

      it('should create an instance of DecodedInput', function() {
        // TODO: update the code to test DecodedInput
        expect(instance).to.be.a(BlockScoutApi.DecodedInput);
      });

      it('should have the property methodCall (base name: "method_call")', function() {
        // TODO: update the code to test the property methodCall
        expect(instance).to.have.property('methodCall');
        // expect(instance.methodCall).to.be(expectedValueLiteral);
      });

      it('should have the property methodId (base name: "method_id")', function() {
        // TODO: update the code to test the property methodId
        expect(instance).to.have.property('methodId');
        // expect(instance.methodId).to.be(expectedValueLiteral);
      });

      it('should have the property parameters (base name: "parameters")', function() {
        // TODO: update the code to test the property parameters
        expect(instance).to.have.property('parameters');
        // expect(instance.parameters).to.be(expectedValueLiteral);
      });

    });
  });

}));
