/*
 * BlockScout API
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BlockScoutApi);
  }
}(this, function(expect, BlockScoutApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('RawTraceSelfDestructAction', function() {
      beforeEach(function() {
        instance = new BlockScoutApi.RawTraceSelfDestructAction();
      });

      it('should create an instance of RawTraceSelfDestructAction', function() {
        // TODO: update the code to test RawTraceSelfDestructAction
        expect(instance).to.be.a(BlockScoutApi.RawTraceSelfDestructAction);
      });

      it('should have the property address (base name: "address")', function() {
        // TODO: update the code to test the property address
        expect(instance).to.have.property('address');
        // expect(instance.address).to.be(expectedValueLiteral);
      });

      it('should have the property balance (base name: "balance")', function() {
        // TODO: update the code to test the property balance
        expect(instance).to.have.property('balance');
        // expect(instance.balance).to.be(expectedValueLiteral);
      });

      it('should have the property refundAddress (base name: "refundAddress")', function() {
        // TODO: update the code to test the property refundAddress
        expect(instance).to.have.property('refundAddress');
        // expect(instance.refundAddress).to.be(expectedValueLiteral);
      });

    });
  });

}));
