/*
 * BlockScout API
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BlockScoutApi);
  }
}(this, function(expect, BlockScoutApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('RawTraceCreateResult', function() {
      beforeEach(function() {
        instance = new BlockScoutApi.RawTraceCreateResult();
      });

      it('should create an instance of RawTraceCreateResult', function() {
        // TODO: update the code to test RawTraceCreateResult
        expect(instance).to.be.a(BlockScoutApi.RawTraceCreateResult);
      });

      it('should have the property address (base name: "address")', function() {
        // TODO: update the code to test the property address
        expect(instance).to.have.property('address');
        // expect(instance.address).to.be(expectedValueLiteral);
      });

      it('should have the property code (base name: "code")', function() {
        // TODO: update the code to test the property code
        expect(instance).to.have.property('code');
        // expect(instance.code).to.be(expectedValueLiteral);
      });

      it('should have the property gasUsed (base name: "gasUsed")', function() {
        // TODO: update the code to test the property gasUsed
        expect(instance).to.have.property('gasUsed');
        // expect(instance.gasUsed).to.be(expectedValueLiteral);
      });

    });
  });

}));
