/*
 * BlockScout API
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BlockScoutApi);
  }
}(this, function(expect, BlockScoutApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ReadMethodQueryBody', function() {
      beforeEach(function() {
        instance = new BlockScoutApi.ReadMethodQueryBody();
      });

      it('should create an instance of ReadMethodQueryBody', function() {
        // TODO: update the code to test ReadMethodQueryBody
        expect(instance).to.be.a(BlockScoutApi.ReadMethodQueryBody);
      });

      it('should have the property args (base name: "args")', function() {
        // TODO: update the code to test the property args
        expect(instance).to.have.property('args');
        // expect(instance.args).to.be(expectedValueLiteral);
      });

      it('should have the property methodId (base name: "method_id")', function() {
        // TODO: update the code to test the property methodId
        expect(instance).to.have.property('methodId');
        // expect(instance.methodId).to.be(expectedValueLiteral);
      });

      it('should have the property from (base name: "from")', function() {
        // TODO: update the code to test the property from
        expect(instance).to.have.property('from');
        // expect(instance.from).to.be(expectedValueLiteral);
      });

      it('should have the property contractType (base name: "contract_type")', function() {
        // TODO: update the code to test the property contractType
        expect(instance).to.have.property('contractType');
        // expect(instance.contractType).to.be(expectedValueLiteral);
      });

    });
  });

}));
