/*
 * BlockScout API
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BlockScoutApi);
  }
}(this, function(expect, BlockScoutApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('SearchResultBlock', function() {
      beforeEach(function() {
        instance = new BlockScoutApi.SearchResultBlock();
      });

      it('should create an instance of SearchResultBlock', function() {
        // TODO: update the code to test SearchResultBlock
        expect(instance).to.be.a(BlockScoutApi.SearchResultBlock);
      });

      it('should have the property blockHash (base name: "block_hash")', function() {
        // TODO: update the code to test the property blockHash
        expect(instance).to.have.property('blockHash');
        // expect(instance.blockHash).to.be(expectedValueLiteral);
      });

      it('should have the property blockNumber (base name: "block_number")', function() {
        // TODO: update the code to test the property blockNumber
        expect(instance).to.have.property('blockNumber');
        // expect(instance.blockNumber).to.be(expectedValueLiteral);
      });

      it('should have the property timestamp (base name: "timestamp")', function() {
        // TODO: update the code to test the property timestamp
        expect(instance).to.have.property('timestamp');
        // expect(instance.timestamp).to.be(expectedValueLiteral);
      });

      it('should have the property type (base name: "type")', function() {
        // TODO: update the code to test the property type
        expect(instance).to.have.property('type');
        // expect(instance.type).to.be(expectedValueLiteral);
      });

      it('should have the property url (base name: "url")', function() {
        // TODO: update the code to test the property url
        expect(instance).to.have.property('url');
        // expect(instance.url).to.be(expectedValueLiteral);
      });

    });
  });

}));
