/*
 * BlockScout API
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BlockScoutApi);
  }
}(this, function(expect, BlockScoutApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('SearchResultRedirect', function() {
      beforeEach(function() {
        instance = new BlockScoutApi.SearchResultRedirect();
      });

      it('should create an instance of SearchResultRedirect', function() {
        // TODO: update the code to test SearchResultRedirect
        expect(instance).to.be.a(BlockScoutApi.SearchResultRedirect);
      });

      it('should have the property parameter (base name: "parameter")', function() {
        // TODO: update the code to test the property parameter
        expect(instance).to.have.property('parameter');
        // expect(instance.parameter).to.be(expectedValueLiteral);
      });

      it('should have the property redirect (base name: "redirect")', function() {
        // TODO: update the code to test the property redirect
        expect(instance).to.have.property('redirect');
        // expect(instance.redirect).to.be(expectedValueLiteral);
      });

      it('should have the property type (base name: "type")', function() {
        // TODO: update the code to test the property type
        expect(instance).to.have.property('type');
        // expect(instance.type).to.be(expectedValueLiteral);
      });

    });
  });

}));
