/*
 * BlockScout API
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BlockScoutApi);
  }
}(this, function(expect, BlockScoutApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('TransactionChartItem', function() {
      beforeEach(function() {
        instance = new BlockScoutApi.TransactionChartItem();
      });

      it('should create an instance of TransactionChartItem', function() {
        // TODO: update the code to test TransactionChartItem
        expect(instance).to.be.a(BlockScoutApi.TransactionChartItem);
      });

      it('should have the property _date (base name: "date")', function() {
        // TODO: update the code to test the property _date
        expect(instance).to.have.property('_date');
        // expect(instance._date).to.be(expectedValueLiteral);
      });

      it('should have the property txCount (base name: "tx_count")', function() {
        // TODO: update the code to test the property txCount
        expect(instance).to.have.property('txCount');
        // expect(instance.txCount).to.be(expectedValueLiteral);
      });

    });
  });

}));
