/*
 * BlockScout API
 * API for BlockScout web app
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from './ApiClient';
import {Address} from './model/Address';
import {AddressCounters} from './model/AddressCounters';
import {AddressParam} from './model/AddressParam';
import {AddressTag} from './model/AddressTag';
import {AddressWithTxCount} from './model/AddressWithTxCount';
import {Argument} from './model/Argument';
import {Block} from './model/Block';
import {CodeAndMessage} from './model/CodeAndMessage';
import {CoinBalanceHistoryByDaysEntry} from './model/CoinBalanceHistoryByDaysEntry';
import {CoinBalanceHistoryEntry} from './model/CoinBalanceHistoryEntry';
import {ConstructorArguments} from './model/ConstructorArguments';
import {ContractSource} from './model/ContractSource';
import {DecodedInput} from './model/DecodedInput';
import {DecodedInputLog} from './model/DecodedInputLog';
import {DecodedInputLogParameter} from './model/DecodedInputLogParameter';
import {DecodedInputParameter} from './model/DecodedInputParameter';
import {ERC20Or1155OrCoinChange} from './model/ERC20Or1155OrCoinChange';
import {Error} from './model/Error';
import {ExtendedRevertReasonAsMap} from './model/ExtendedRevertReasonAsMap';
import {ExternalLibrary} from './model/ExternalLibrary';
import {Fee} from './model/Fee';
import {Holder} from './model/Holder';
import {IndexingStatus} from './model/IndexingStatus';
import {InlineResponse200} from './model/InlineResponse200';
import {InlineResponse2001} from './model/InlineResponse2001';
import {InlineResponse20010} from './model/InlineResponse20010';
import {InlineResponse20011} from './model/InlineResponse20011';
import {InlineResponse20012} from './model/InlineResponse20012';
import {InlineResponse20013} from './model/InlineResponse20013';
import {InlineResponse20014} from './model/InlineResponse20014';
import {InlineResponse20015} from './model/InlineResponse20015';
import {InlineResponse20016} from './model/InlineResponse20016';
import {InlineResponse20017} from './model/InlineResponse20017';
import {InlineResponse20018} from './model/InlineResponse20018';
import {InlineResponse20019} from './model/InlineResponse20019';
import {InlineResponse2002} from './model/InlineResponse2002';
import {InlineResponse20020} from './model/InlineResponse20020';
import {InlineResponse20021} from './model/InlineResponse20021';
import {InlineResponse20022} from './model/InlineResponse20022';
import {InlineResponse20023} from './model/InlineResponse20023';
import {InlineResponse20024} from './model/InlineResponse20024';
import {InlineResponse20025} from './model/InlineResponse20025';
import {InlineResponse20026} from './model/InlineResponse20026';
import {InlineResponse20027} from './model/InlineResponse20027';
import {InlineResponse2003} from './model/InlineResponse2003';
import {InlineResponse2004} from './model/InlineResponse2004';
import {InlineResponse2005} from './model/InlineResponse2005';
import {InlineResponse2006} from './model/InlineResponse2006';
import {InlineResponse2007} from './model/InlineResponse2007';
import {InlineResponse2008} from './model/InlineResponse2008';
import {InlineResponse2009} from './model/InlineResponse2009';
import {InternalTransaction} from './model/InternalTransaction';
import {Log} from './model/Log';
import {MarketChartItem} from './model/MarketChartItem';
import {NFTChange} from './model/NFTChange';
import {NFTChangesArray} from './model/NFTChangesArray';
import {NFTInstance} from './model/NFTInstance';
import {OneOfRawTraceAction} from './model/OneOfRawTraceAction';
import {OneOfRawTraceResult} from './model/OneOfRawTraceResult';
import {OneOfReadMethodResponseResult} from './model/OneOfReadMethodResponseResult';
import {OneOfStateChangeChange} from './model/OneOfStateChangeChange';
import {OneOfTokenTransferTotal} from './model/OneOfTokenTransferTotal';
import {OneOfinlineResponse200ItemsItems} from './model/OneOfinlineResponse200ItemsItems';
import {OutputAndNames} from './model/OutputAndNames';
import {RawTrace} from './model/RawTrace';
import {RawTraceCallAction} from './model/RawTraceCallAction';
import {RawTraceCallResult} from './model/RawTraceCallResult';
import {RawTraceCreateAction} from './model/RawTraceCreateAction';
import {RawTraceCreateResult} from './model/RawTraceCreateResult';
import {RawTraceSelfDestructAction} from './model/RawTraceSelfDestructAction';
import {ReadMethodQueryBody} from './model/ReadMethodQueryBody';
import {ReadMethodResponse} from './model/ReadMethodResponse';
import {ReadMethodWithValue} from './model/ReadMethodWithValue';
import {ReadMethodWithoutValue} from './model/ReadMethodWithoutValue';
import {Reward} from './model/Reward';
import {SearchResultAddressOrContract} from './model/SearchResultAddressOrContract';
import {SearchResultBlock} from './model/SearchResultBlock';
import {SearchResultRedirect} from './model/SearchResultRedirect';
import {SearchResultToken} from './model/SearchResultToken';
import {SearchResultTransaction} from './model/SearchResultTransaction';
import {SmartContract} from './model/SmartContract';
import {SmartContractForList} from './model/SmartContractForList';
import {StateChange} from './model/StateChange';
import {StatsResponse} from './model/StatsResponse';
import {Token} from './model/Token';
import {TokenBalance} from './model/TokenBalance';
import {TokenCounters} from './model/TokenCounters';
import {TokenInfo} from './model/TokenInfo';
import {TokenTransfer} from './model/TokenTransfer';
import {TotalERC1155} from './model/TotalERC1155';
import {TotalERC1155Batch} from './model/TotalERC1155Batch';
import {TotalERC20} from './model/TotalERC20';
import {TotalERC721} from './model/TotalERC721';
import {Transaction} from './model/Transaction';
import {TransactionAction} from './model/TransactionAction';
import {TransactionActionAaveV3BSWRF} from './model/TransactionActionAaveV3BSWRF';
import {TransactionActionAaveV3EnableDisableCollateral} from './model/TransactionActionAaveV3EnableDisableCollateral';
import {TransactionActionAaveV3LiquidationCall} from './model/TransactionActionAaveV3LiquidationCall';
import {TransactionActionUniswapV3BCS} from './model/TransactionActionUniswapV3BCS';
import {TransactionActionUniswapV3MintNFT} from './model/TransactionActionUniswapV3MintNFT';
import {TransactionChartItem} from './model/TransactionChartItem';
import {TransactionReward} from './model/TransactionReward';
import {WatchlistName} from './model/WatchlistName';
import {Withdrawal} from './model/Withdrawal';
import {WriteMethod} from './model/WriteMethod';
import {DefaultApi} from './api/DefaultApi';

/**
* API_for_BlockScout_web_app.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var BlockScoutApi = require('index'); // See note below*.
* var xxxSvc = new BlockScoutApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new BlockScoutApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new BlockScoutApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new BlockScoutApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Address model constructor.
     * @property {module:model/Address}
     */
    Address,

    /**
     * The AddressCounters model constructor.
     * @property {module:model/AddressCounters}
     */
    AddressCounters,

    /**
     * The AddressParam model constructor.
     * @property {module:model/AddressParam}
     */
    AddressParam,

    /**
     * The AddressTag model constructor.
     * @property {module:model/AddressTag}
     */
    AddressTag,

    /**
     * The AddressWithTxCount model constructor.
     * @property {module:model/AddressWithTxCount}
     */
    AddressWithTxCount,

    /**
     * The Argument model constructor.
     * @property {module:model/Argument}
     */
    Argument,

    /**
     * The Block model constructor.
     * @property {module:model/Block}
     */
    Block,

    /**
     * The CodeAndMessage model constructor.
     * @property {module:model/CodeAndMessage}
     */
    CodeAndMessage,

    /**
     * The CoinBalanceHistoryByDaysEntry model constructor.
     * @property {module:model/CoinBalanceHistoryByDaysEntry}
     */
    CoinBalanceHistoryByDaysEntry,

    /**
     * The CoinBalanceHistoryEntry model constructor.
     * @property {module:model/CoinBalanceHistoryEntry}
     */
    CoinBalanceHistoryEntry,

    /**
     * The ConstructorArguments model constructor.
     * @property {module:model/ConstructorArguments}
     */
    ConstructorArguments,

    /**
     * The ContractSource model constructor.
     * @property {module:model/ContractSource}
     */
    ContractSource,

    /**
     * The DecodedInput model constructor.
     * @property {module:model/DecodedInput}
     */
    DecodedInput,

    /**
     * The DecodedInputLog model constructor.
     * @property {module:model/DecodedInputLog}
     */
    DecodedInputLog,

    /**
     * The DecodedInputLogParameter model constructor.
     * @property {module:model/DecodedInputLogParameter}
     */
    DecodedInputLogParameter,

    /**
     * The DecodedInputParameter model constructor.
     * @property {module:model/DecodedInputParameter}
     */
    DecodedInputParameter,

    /**
     * The ERC20Or1155OrCoinChange model constructor.
     * @property {module:model/ERC20Or1155OrCoinChange}
     */
    ERC20Or1155OrCoinChange,

    /**
     * The Error model constructor.
     * @property {module:model/Error}
     */
    Error,

    /**
     * The ExtendedRevertReasonAsMap model constructor.
     * @property {module:model/ExtendedRevertReasonAsMap}
     */
    ExtendedRevertReasonAsMap,

    /**
     * The ExternalLibrary model constructor.
     * @property {module:model/ExternalLibrary}
     */
    ExternalLibrary,

    /**
     * The Fee model constructor.
     * @property {module:model/Fee}
     */
    Fee,

    /**
     * The Holder model constructor.
     * @property {module:model/Holder}
     */
    Holder,

    /**
     * The IndexingStatus model constructor.
     * @property {module:model/IndexingStatus}
     */
    IndexingStatus,

    /**
     * The InlineResponse200 model constructor.
     * @property {module:model/InlineResponse200}
     */
    InlineResponse200,

    /**
     * The InlineResponse2001 model constructor.
     * @property {module:model/InlineResponse2001}
     */
    InlineResponse2001,

    /**
     * The InlineResponse20010 model constructor.
     * @property {module:model/InlineResponse20010}
     */
    InlineResponse20010,

    /**
     * The InlineResponse20011 model constructor.
     * @property {module:model/InlineResponse20011}
     */
    InlineResponse20011,

    /**
     * The InlineResponse20012 model constructor.
     * @property {module:model/InlineResponse20012}
     */
    InlineResponse20012,

    /**
     * The InlineResponse20013 model constructor.
     * @property {module:model/InlineResponse20013}
     */
    InlineResponse20013,

    /**
     * The InlineResponse20014 model constructor.
     * @property {module:model/InlineResponse20014}
     */
    InlineResponse20014,

    /**
     * The InlineResponse20015 model constructor.
     * @property {module:model/InlineResponse20015}
     */
    InlineResponse20015,

    /**
     * The InlineResponse20016 model constructor.
     * @property {module:model/InlineResponse20016}
     */
    InlineResponse20016,

    /**
     * The InlineResponse20017 model constructor.
     * @property {module:model/InlineResponse20017}
     */
    InlineResponse20017,

    /**
     * The InlineResponse20018 model constructor.
     * @property {module:model/InlineResponse20018}
     */
    InlineResponse20018,

    /**
     * The InlineResponse20019 model constructor.
     * @property {module:model/InlineResponse20019}
     */
    InlineResponse20019,

    /**
     * The InlineResponse2002 model constructor.
     * @property {module:model/InlineResponse2002}
     */
    InlineResponse2002,

    /**
     * The InlineResponse20020 model constructor.
     * @property {module:model/InlineResponse20020}
     */
    InlineResponse20020,

    /**
     * The InlineResponse20021 model constructor.
     * @property {module:model/InlineResponse20021}
     */
    InlineResponse20021,

    /**
     * The InlineResponse20022 model constructor.
     * @property {module:model/InlineResponse20022}
     */
    InlineResponse20022,

    /**
     * The InlineResponse20023 model constructor.
     * @property {module:model/InlineResponse20023}
     */
    InlineResponse20023,

    /**
     * The InlineResponse20024 model constructor.
     * @property {module:model/InlineResponse20024}
     */
    InlineResponse20024,

    /**
     * The InlineResponse20025 model constructor.
     * @property {module:model/InlineResponse20025}
     */
    InlineResponse20025,

    /**
     * The InlineResponse20026 model constructor.
     * @property {module:model/InlineResponse20026}
     */
    InlineResponse20026,

    /**
     * The InlineResponse20027 model constructor.
     * @property {module:model/InlineResponse20027}
     */
    InlineResponse20027,

    /**
     * The InlineResponse2003 model constructor.
     * @property {module:model/InlineResponse2003}
     */
    InlineResponse2003,

    /**
     * The InlineResponse2004 model constructor.
     * @property {module:model/InlineResponse2004}
     */
    InlineResponse2004,

    /**
     * The InlineResponse2005 model constructor.
     * @property {module:model/InlineResponse2005}
     */
    InlineResponse2005,

    /**
     * The InlineResponse2006 model constructor.
     * @property {module:model/InlineResponse2006}
     */
    InlineResponse2006,

    /**
     * The InlineResponse2007 model constructor.
     * @property {module:model/InlineResponse2007}
     */
    InlineResponse2007,

    /**
     * The InlineResponse2008 model constructor.
     * @property {module:model/InlineResponse2008}
     */
    InlineResponse2008,

    /**
     * The InlineResponse2009 model constructor.
     * @property {module:model/InlineResponse2009}
     */
    InlineResponse2009,

    /**
     * The InternalTransaction model constructor.
     * @property {module:model/InternalTransaction}
     */
    InternalTransaction,

    /**
     * The Log model constructor.
     * @property {module:model/Log}
     */
    Log,

    /**
     * The MarketChartItem model constructor.
     * @property {module:model/MarketChartItem}
     */
    MarketChartItem,

    /**
     * The NFTChange model constructor.
     * @property {module:model/NFTChange}
     */
    NFTChange,

    /**
     * The NFTChangesArray model constructor.
     * @property {module:model/NFTChangesArray}
     */
    NFTChangesArray,

    /**
     * The NFTInstance model constructor.
     * @property {module:model/NFTInstance}
     */
    NFTInstance,

    /**
     * The OneOfRawTraceAction model constructor.
     * @property {module:model/OneOfRawTraceAction}
     */
    OneOfRawTraceAction,

    /**
     * The OneOfRawTraceResult model constructor.
     * @property {module:model/OneOfRawTraceResult}
     */
    OneOfRawTraceResult,

    /**
     * The OneOfReadMethodResponseResult model constructor.
     * @property {module:model/OneOfReadMethodResponseResult}
     */
    OneOfReadMethodResponseResult,

    /**
     * The OneOfStateChangeChange model constructor.
     * @property {module:model/OneOfStateChangeChange}
     */
    OneOfStateChangeChange,

    /**
     * The OneOfTokenTransferTotal model constructor.
     * @property {module:model/OneOfTokenTransferTotal}
     */
    OneOfTokenTransferTotal,

    /**
     * The OneOfinlineResponse200ItemsItems model constructor.
     * @property {module:model/OneOfinlineResponse200ItemsItems}
     */
    OneOfinlineResponse200ItemsItems,

    /**
     * The OutputAndNames model constructor.
     * @property {module:model/OutputAndNames}
     */
    OutputAndNames,

    /**
     * The RawTrace model constructor.
     * @property {module:model/RawTrace}
     */
    RawTrace,

    /**
     * The RawTraceCallAction model constructor.
     * @property {module:model/RawTraceCallAction}
     */
    RawTraceCallAction,

    /**
     * The RawTraceCallResult model constructor.
     * @property {module:model/RawTraceCallResult}
     */
    RawTraceCallResult,

    /**
     * The RawTraceCreateAction model constructor.
     * @property {module:model/RawTraceCreateAction}
     */
    RawTraceCreateAction,

    /**
     * The RawTraceCreateResult model constructor.
     * @property {module:model/RawTraceCreateResult}
     */
    RawTraceCreateResult,

    /**
     * The RawTraceSelfDestructAction model constructor.
     * @property {module:model/RawTraceSelfDestructAction}
     */
    RawTraceSelfDestructAction,

    /**
     * The ReadMethodQueryBody model constructor.
     * @property {module:model/ReadMethodQueryBody}
     */
    ReadMethodQueryBody,

    /**
     * The ReadMethodResponse model constructor.
     * @property {module:model/ReadMethodResponse}
     */
    ReadMethodResponse,

    /**
     * The ReadMethodWithValue model constructor.
     * @property {module:model/ReadMethodWithValue}
     */
    ReadMethodWithValue,

    /**
     * The ReadMethodWithoutValue model constructor.
     * @property {module:model/ReadMethodWithoutValue}
     */
    ReadMethodWithoutValue,

    /**
     * The Reward model constructor.
     * @property {module:model/Reward}
     */
    Reward,

    /**
     * The SearchResultAddressOrContract model constructor.
     * @property {module:model/SearchResultAddressOrContract}
     */
    SearchResultAddressOrContract,

    /**
     * The SearchResultBlock model constructor.
     * @property {module:model/SearchResultBlock}
     */
    SearchResultBlock,

    /**
     * The SearchResultRedirect model constructor.
     * @property {module:model/SearchResultRedirect}
     */
    SearchResultRedirect,

    /**
     * The SearchResultToken model constructor.
     * @property {module:model/SearchResultToken}
     */
    SearchResultToken,

    /**
     * The SearchResultTransaction model constructor.
     * @property {module:model/SearchResultTransaction}
     */
    SearchResultTransaction,

    /**
     * The SmartContract model constructor.
     * @property {module:model/SmartContract}
     */
    SmartContract,

    /**
     * The SmartContractForList model constructor.
     * @property {module:model/SmartContractForList}
     */
    SmartContractForList,

    /**
     * The StateChange model constructor.
     * @property {module:model/StateChange}
     */
    StateChange,

    /**
     * The StatsResponse model constructor.
     * @property {module:model/StatsResponse}
     */
    StatsResponse,

    /**
     * The Token model constructor.
     * @property {module:model/Token}
     */
    Token,

    /**
     * The TokenBalance model constructor.
     * @property {module:model/TokenBalance}
     */
    TokenBalance,

    /**
     * The TokenCounters model constructor.
     * @property {module:model/TokenCounters}
     */
    TokenCounters,

    /**
     * The TokenInfo model constructor.
     * @property {module:model/TokenInfo}
     */
    TokenInfo,

    /**
     * The TokenTransfer model constructor.
     * @property {module:model/TokenTransfer}
     */
    TokenTransfer,

    /**
     * The TotalERC1155 model constructor.
     * @property {module:model/TotalERC1155}
     */
    TotalERC1155,

    /**
     * The TotalERC1155Batch model constructor.
     * @property {module:model/TotalERC1155Batch}
     */
    TotalERC1155Batch,

    /**
     * The TotalERC20 model constructor.
     * @property {module:model/TotalERC20}
     */
    TotalERC20,

    /**
     * The TotalERC721 model constructor.
     * @property {module:model/TotalERC721}
     */
    TotalERC721,

    /**
     * The Transaction model constructor.
     * @property {module:model/Transaction}
     */
    Transaction,

    /**
     * The TransactionAction model constructor.
     * @property {module:model/TransactionAction}
     */
    TransactionAction,

    /**
     * The TransactionActionAaveV3BSWRF model constructor.
     * @property {module:model/TransactionActionAaveV3BSWRF}
     */
    TransactionActionAaveV3BSWRF,

    /**
     * The TransactionActionAaveV3EnableDisableCollateral model constructor.
     * @property {module:model/TransactionActionAaveV3EnableDisableCollateral}
     */
    TransactionActionAaveV3EnableDisableCollateral,

    /**
     * The TransactionActionAaveV3LiquidationCall model constructor.
     * @property {module:model/TransactionActionAaveV3LiquidationCall}
     */
    TransactionActionAaveV3LiquidationCall,

    /**
     * The TransactionActionUniswapV3BCS model constructor.
     * @property {module:model/TransactionActionUniswapV3BCS}
     */
    TransactionActionUniswapV3BCS,

    /**
     * The TransactionActionUniswapV3MintNFT model constructor.
     * @property {module:model/TransactionActionUniswapV3MintNFT}
     */
    TransactionActionUniswapV3MintNFT,

    /**
     * The TransactionChartItem model constructor.
     * @property {module:model/TransactionChartItem}
     */
    TransactionChartItem,

    /**
     * The TransactionReward model constructor.
     * @property {module:model/TransactionReward}
     */
    TransactionReward,

    /**
     * The WatchlistName model constructor.
     * @property {module:model/WatchlistName}
     */
    WatchlistName,

    /**
     * The Withdrawal model constructor.
     * @property {module:model/Withdrawal}
     */
    Withdrawal,

    /**
     * The WriteMethod model constructor.
     * @property {module:model/WriteMethod}
     */
    WriteMethod,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi
};
